" Pathogen

execute pathogen#infect()

" Material theme

set background=dark
colorscheme hybrid_material
let g:enable_bold_font = 1
let g:enable_italic_font = 1

" Configuration

filetype plugin indent on
set backspace=indent,eol,start
set cindent
set noexpandtab
set number
set scrolloff=9999
set shiftwidth=4
set softtabstop=0
set tabstop=4
set wrap!
syntax on

if &term =~ '256color'
	set t_ut=
endif
