# zsh
export ZSH=~/.oh-my-zsh
DISABLE_UPDATE_PROMPT=true
ZSH_THEME="custom"
plugins=(git zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# general
alias gdb="gdb -q"
alias ping-cs="ping data.cs.purdue.edu"
alias sftp-cs="sftp smangiap@data.cs.purdue.edu"
alias ssh-cs="ssh smangiap@data.cs.purdue.edu"
export EDITOR='vim'
export PAGER="less -S"
export PATH=~"/.bin:${PATH}"
export SSH_KEY_PATH="~/.ssh/id_rsa"
export TERM="xterm-256color"
unsetopt share_history

# custom
source ~/.zshrc_custom
