function git_branch_name()
{
  branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
  if [[ $branch == "" ]];
  then
    :
  else
    echo ' %F{red}'$branch'%f'
  fi
}

setopt prompt_subst

PROMPT='%B%F{green}zsh%f %F{blue}%c%f$(git_branch_name)%b '
