# zsh
export ZSH=~/.oh-my-zsh
DISABLE_UPDATE_PROMPT=true
ZSH_THEME="custom"
plugins=(git zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh

# general
alias gdb="gdb -q"
export EDITOR='vim'
export PAGER="less -S"
export PATH=~"/.bin:${PATH}"
export SSH_KEY_PATH="~/.ssh/id_rsa"
export TERM="xterm-256color"
unsetopt share_history

# local configuration
if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi
